version: 2

project_name: ansicube

before:
  hooks:
    - go mod tidy

builds:
  - id: ansicube
    main: .
    binary: ansicube
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: ansicube
    repository:
      owner: maxludden
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/maxludden/ansiCube"
    description: "Interactive ANSI 256-color explorer for the terminal"
    license: "MIT"
    commit_author:
      name: Max Ludden
      email: maxludden@users.noreply.github.com
